language: node_js
sudo: required
node_js:
  - '8'
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
branches:
  only: master
script:
  - rm -rf example-dist
  - npm run lint
  - npm run build:gh
after_script:
  - cd example-dist
  - git init
  - git config user.name "hwen"
  - git config user.email "hwenleung@gmail.com"
  - git add .
  - git commit -m "Travis build docs"
  - git push  --force --quiet "https://${GITHUB_TOKEN}@github.com/SME-FE/smv-modal.git" master:gh-pages
